schema_version = "1.0.0"

id = "recalculate_origin_orientation"
name = "Recalculate Origin Orientation"
tagline = "Recalculate an object's origin orientation to the selected face normal"
version = "1.0.0"
maintainer = "Endertainer007 <endertainer@protonmail.com>"
type = "add-on"
tags = ["User Interface", "Object", "Mesh", "Modeling", "Scene"]
blender_version_min = "4.4.0"
license = ["SPDX:GPL-3.0-or-later"]